mode: debug # Debug Online

server:
  port: :3001

log_zap:
  #日志级别 -1 Debug, -2 Info, -3 Warn, -4 Error, -5 DPanic, -6Panic, -7Fatal
  level: -1
  # 日志输出 1 控制台  2 文件  3 控制台+文件
  output: 3

log_file:
  file_name: "./log/dev.log"
  max_size: 128
  max_backups: 3
  max_age: 7
  compress: true

redis:
  enable: false
  host: 127.0.0.1
  port: 6379
  password: "password"

db:
  # 连接地址
  host: localhost
  # 连接端口
  port: 3306
  # 用户名
  user: cufoon
  # 密码
  password: 123
  # 数据库
  db_name: litkeep
  # 连接参数
  parameters: charset=utf8&parseTime=True&loc=Local

gorm:
  # 是否开启调试模式
  debug: true
  # 设置连接可以重用的最长时间(单位：秒)
  max_lifetime: 7200
  # 设置数据库的最大打开连接数
  max_open_connections: 150
  # 设置空闲连接池中的最大连接数
  max_idle_connections: 50
